export const AdvertDB = [
  {
    image: "https://drive.usercontent.google.com/download?id=1Kai8n9MKcY-648IdkNU1Zf0KlVuZy7uv",
    href: "https://www.superbet.ro",
    title: "advert 1",
    description: "descriere 1",
    promoCode: "dsadas",
    isEnabled: true,
    from: "07-20-2024",
    to: "07-20-2024",
    page: [],
    secondary: false,
    rate: "5",
    collapsed: false
  },
  {
    image: "https://drive.usercontent.google.com/download?id=1Kai8n9MKcY-648IdkNU1Zf0KlVuZy7uv",
    href: "https://www.superbet.ro",
    title: "advert 2",
    description: "descriere 2",
    promoCode: "",
    isEnabled: true,
    from: "07-20-2024",
    to: "07-20-2024",
    page: ["slots"],
    secondary: false,
    rate: "5",
    collapsed: false
  },
  {
    image: "https://drive.usercontent.google.com/download?id=1Kai8n9MKcY-648IdkNU1Zf0KlVuZy7uv",
    href: "https://www.superbet.ro",
    title: "advert 3",
    description: "descriere 3",
    promoCode: "",
    isEnabled: true,
    from: "07-20-2024",
    to: "07-20-2024",
    page: [],
    secondary: false,
    rate: "5",
    collapsed: false
  },
  {
    image: "https://drive.usercontent.google.com/download?id=1Kai8n9MKcY-648IdkNU1Zf0KlVuZy7uv",
    href: "https://www.superbet.ro",
    title: "advert 1",
    description: "descriere 1",
    promoCode: "",
    isEnabled: true,
    from: "07-20-2024",
    to: "07-20-2024",
    page: ["slots,home"],
    secondary: true,
    rate: "5",
    collapsed: false
  },
  {
    image: "https://drive.usercontent.google.com/download?id=1Kai8n9MKcY-648IdkNU1Zf0KlVuZy7uv",
    href: "https://www.superbet.ro",
    title: "advert 1",
    description: "descriere 1",
    promoCode: "",
    isEnabled: true,
    from: "07-20-2024",
    to: "07-20-2024",
    page: ["slots"],
    secondary: true,
    rate: "5",
    collapsed: true
  },
  {
    image: "https://drive.usercontent.google.com/download?id=1Kai8n9MKcY-648IdkNU1Zf0KlVuZy7uv",
    href: "https://www.superbet.ro",
    title: "advert 1",
    description: "descriere 1",
    promoCode: "",
    isEnabled: true,
    from: "07-20-2024",
    to: "07-20-2024",
    page: ["slots,home"],
    secondary: true,
    rate: "5",
    collapsed: false
  },
  {
    image: "https://drive.usercontent.google.com/download?id=1Kai8n9MKcY-648IdkNU1Zf0KlVuZy7uv",
    href: "https://www.superbet.ro",
    title: "advert 1",
    description: "descriere 1",
    promoCode: "",
    isEnabled: true,
    from: "07-20-2024",
    to: "07-20-2024",
    page: ["slots"],
    secondary: true,
    rate: "5",
    collapsed: true
  },
  {
    image: "https://drive.usercontent.google.com/download?id=1Kai8n9MKcY-648IdkNU1Zf0KlVuZy7uv",
    href: "https://www.superbet.ro",
    title: "advert 1",
    description: "descriere 1",
    promoCode: "",
    isEnabled: true,
    from: "07-20-2024",
    to: "07-20-2024",
    page: ["slots,home"],
    secondary: true,
    rate: "5",
    collapsed: false
  },
  {
    image: "https://drive.usercontent.google.com/download?id=1Kai8n9MKcY-648IdkNU1Zf0KlVuZy7uv",
    href: "https://www.superbet.ro",
    title: "advert 1",
    description: "descriere 1",
    promoCode: "",
    isEnabled: true,
    from: "07-20-2024",
    to: "07-20-2024",
    page: ["slots"],
    secondary: true,
    rate: "5",
    collapsed: true
  }
]
