export const gamesDB = [
  {
    id: "1065474",
    title: "Spin & Collect 5",
    type: "slot",
    min_bet: "0.5",
    max_bet: "500",
    lines: "5",
    reels: "3",
    rtp: "≈ 97%",
    demo: "https://demo.championstudio.net/?p=%7B%22back_url%22%3A%20%22https%3A//games.champion.tm/game/92/%22%2C%20%22game_id%22%3A%201089%2C%20%22login_code%22%3A%20%22%5B%5B00000000000000%5D%5D%22%2C%20%22game_exit%22%3A%20%22%5B%5Bclose%5D%5D%22%7D&demo_token=chgsol4ukpnulren7tm",
    link_game_info: "https://games.champion.tm/en/game/92/",
    game_assets:
      "https://drive.usercontent.google.com/download?id=10z7-OqcDoBco2TJch1mLSRDu6eLfbS4R,https://drive.usercontent.google.com/download?id=1ARw0E8HvA5nfGYRLD6WkCxyllDMGpJbn",
    game_assets_2: "",
    global_game_launch: "12-04-2023",
    provider: "1Spin4Win",
    features: ["MegaWays", "Bonus Buy", "Progressive"],
    theme: "Fruit",
    volatility: "medium"
  },
  {
    id: "1675073",
    title: "Bistro",
    type: "slot",
    min_bet: "1",
    max_bet: "1000",
    lines: "10",
    reels: "5",
    rtp: "≈ 97%",
    demo: "https://demo.championstudio.net/?p=%7B%22back_url%22%3A%20%22https%3A//games.champion.tm/game/91/%22%2C%20%22game_id%22%3A%201088%2C%20%22login_code%22%3A%20%22%5B%5B00000000000000%5D%5D%22%2C%20%22game_exit%22%3A%20%22%5B%5Bclose%5D%5D%22%7D&demo_token=chgsol4ukpnulren7tm",
    link_game_info: "https://games.champion.tm/en/game/91/",
    game_assets:
      "https://drive.usercontent.google.com/download?id=14j0Z1oRwvZfUM3uIHwfkGWxFbAz45B1m,https://drive.usercontent.google.com/download?id=1fhQdT-t2b3b2msikUi5pLMKbirfvdreZ",
    game_assets_2: "",
    global_game_launch: "11-20-2023",
    provider: "AllWaySpin",
    features: ["Land Based", "Cluster slot", "Autoplay"],
    theme: "Christmas",
    volatility: "low-medium"
  },
  {
    id: "107432",
    title: "Fire Bell",
    type: "slot",
    min_bet: "0.5",
    max_bet: "500",
    lines: "5",
    reels: "3",
    rtp: "≈ 97%",
    demo: "https://demo.championstudio.net/?p=%7B%22back_url%22%3A%20%22https%3A//games.champion.tm/game/90/%22%2C%20%22game_id%22%3A%201087%2C%20%22login_code%22%3A%20%22%5B%5B00000000000000%5D%5D%22%2C%20%22game_exit%22%3A%20%22%5B%5Bclose%5D%5D%22%7D&demo_token=chgsol4ukpnulren7tm",
    link_game_info: "https://games.champion.tm/en/game/90/",
    game_assets:
      "https://drive.usercontent.google.com/download?id=1dInSkEUj5r1Xel_bRxCTxKIoyG2jRQvu,https://drive.usercontent.google.com/download?id=1-Nk_B9ctpb1bS--v2pQFUN0ocbw9xCq",
    game_assets_2: "",
    global_game_launch: "10-05-2023",
    provider: "AlchemyGaming",
    features: ["Quickspin", "Tumbling reels", "Increasing multipliers"],
    theme: "Halloween",
    volatility: "medium-high"
  },
  {
    id: "104371",
    title: "Cyber Hunt",
    type: "slot",
    min_bet: "0.1",
    max_bet: "1500",
    lines: "15",
    reels: "5",
    rtp: "≈ 97%",
    demo: 'https://demo.championstudio.net/?p={"game_id": 1086, "login_code": "[[00000000000000]]"}',
    link_game_info: "https://games.champion.tm/en/game/88/",
    game_assets:
      "https://drive.usercontent.google.com/download?id=1w_DIeMD6fHEDZrT8lwWtvMFQuDRHHEEU,https://drive.usercontent.google.com/download?id=15UGtPE_BUK8i5sdrXSMu9orhQZCYEag6",
    game_assets_2: "",
    global_game_launch: "08-16-2023",
    provider: "Air Dice",
    features: ["MegaWays", "Bonus Buy", "Progressive"],
    theme: "Candy",
    volatility: "high"
  },
  {
    id: "104370",
    title: "Buffalo Wheel",
    type: "slot",
    min_bet: "5",
    max_bet: "5000",
    lines: "50",
    reels: "5",
    rtp: "≈ 97%",
    demo: 'https://demo.championstudio.net/?p={"game_id": 1085, "login_code": "[[00000000000000]]"}',
    link_game_info: "https://games.champion.tm/en/game/87/",
    game_assets:
      "https://drive.usercontent.google.com/download?id=1KS52Ay7OPVk0V8HIdHdDSYFYbt1haeJh,https://drive.usercontent.google.com/download?id=1atjfRXF8uMmsQ586deQjFqMwLLVQVphB",
    game_assets_2: "",
    global_game_launch: "07-27-2023",
    provider: "AlchemyGaming",
    features: ["Quickspin", "Tumbling reels", "Increasing multipliers"],
    theme: "Cat",
    volatility: "low"
  },
  {
    id: "133069",
    title: "Texas' Heist",
    type: "slot",
    min_bet: "1.5",
    max_bet: "1500",
    lines: "15",
    reels: "5",
    rtp: "≈ 97%",
    demo: 'https://demo.championstudio.net/?p={"game_id": 1084, "login_code": "[[00000000000000]]"}',
    link_game_info: "https://games.champion.tm/en/game/86/",
    game_assets:
      "https://drive.usercontent.google.com/download?id=1VKonNqXAgirNYknsQkbIcLU54-7Unpwo,https://drive.usercontent.google.com/download?id=1QaY4bv6jGStl3jw9qwithbQexFSJvX-U",
    game_assets_2: "",
    global_game_launch: "05-10-2023",
    provider: "Air Dice",
    features: ["Land Based", "Cluster slot", "Autoplay"],
    theme: "Cleopatra",
    volatility: "very-high"
  },
  {
    id: "105568",
    title: "Griffon",
    type: "slot",
    min_bet: "1.5",
    max_bet: "1500",
    lines: "15",
    reels: "5",
    rtp: "≈ 97%",
    demo: 'https://demo.championstudio.net/?p={"game_id": 1083, "login_code": "[[00000000000000]]"}',
    link_game_info: "https://games.champion.tm/en/game/85/",
    game_assets:
      "https://drive.usercontent.google.com/download?id=1LAimkib2FJsettomsvZ1AreMaqPVdSVY,https://drive.usercontent.google.com/download?id=12WQyxmaf3suWdlXXqjTL0_rJqVHyTB2X",
    game_assets_2: "",
    global_game_launch: "04-10-2023",
    provider: "AllWaySpin",
    features: ["Quickspin", "Tumbling reels", "Increasing multipliers"],
    theme: "Coin",
    volatility: "high"
  },
  {
    id: "10367",
    title: "Cassiopeia",
    type: "slot",
    min_bet: "0.1",
    max_bet: "1500",
    lines: "15",
    reels: "5",
    rtp: "≈ 97%",
    demo: "https://demo.championstudio.net/?p=%7B%22game_id%22:%201082,%20%22login_code%22:%20%22[[00000000000000]]%22%7D",
    link_game_info: "https://games.champion.tm/en/game/84/",
    game_assets:
      "https://drive.usercontent.google.com/download?id=163B4GvJt9MKlFSC27sv2JXH0YMkrGQNi,https://drive.usercontent.google.com/download?id=1FrDcm9VzgTLPqp4pjZmqZp9v09kmCxat",
    game_assets_2: "",
    global_game_launch: "03-09-2023",
    provider: "Air Dice",
    features: ["Land Based", "Cluster slot", "Autoplay"],
    theme: "Easter",
    volatility: "medium-high"
  },
  {
    id: "10466",
    title: "Champion Club",
    type: "slot",
    min_bet: "0.5",
    max_bet: "500",
    lines: "5",
    reels: "3",
    rtp: "≈ 97%",
    demo: 'https://demo.championstudio.net/?p={"game_id": 1081, "login_code": "[[00000000000000]]"}',
    link_game_info: "https://games.champion.tm/en/game/83/",
    game_assets:
      "https://drive.usercontent.google.com/download?id=13_srqw3J_dmoTAHwOl41Txbzct0t0n08,https://drive.usercontent.google.com/download?id=1t7hRgP5jRIGTBbnWy90eMCa6_5HwF53G",
    game_assets_2: "",
    global_game_launch: "01-09-2023",
    provider: "AllWaySpin",
    features: ["Land Based", "Cluster slot", "Autoplay"],
    theme: "Gem",
    volatility: "medium"
  },
  {
    id: "10653",
    title: "Wild Alchemist",
    type: "slot",
    min_bet: "0.1",
    max_bet: "1500",
    lines: "15",
    reels: "5",
    rtp: "≈ 97%",
    demo: 'https://demo.championstudio.net/?p={"game_id": 1080, "login_code": "[[00000000000000]]"}',
    link_game_info: "https://games.champion.tm/en/game/82/",
    game_assets:
      "https://drive.usercontent.google.com/download?id=1uh9k5Q7rJUXrbnecZeNVEw4hZKiOElml,https://drive.usercontent.google.com/download?id=13klF-I6BiWjq0voCQ1q5HNYS50iA7nOX",
    game_assets_2: "",
    global_game_launch: "11-11-2022",
    provider: "1Spin4Win",
    features: ["Quickspin", "Tumbling reels", "Increasing multipliers"],
    theme: "Joker",
    volatility: "low"
  },
  {
    id: "10642",
    title: "Balloon Boom",
    type: "slot",
    min_bet: "2",
    max_bet: "2000",
    lines: "-",
    reels: "6",
    rtp: "≈ 97%",
    demo: 'https://demo.championstudio.net/?p={"game_id": 1079, "login_code": "[[00000000000000]]"}',
    link_game_info: "https://games.champion.tm/en/game/80/",
    game_assets:
      "https://drive.usercontent.google.com/download?id=10z7-OqcDoBco2TJch1mLSRDu6eLfbS4R,https://drive.usercontent.google.com/download?id=1ARw0E8HvA5nfGYRLD6WkCxyllDMGpJbn",
    game_assets_2: "",
    global_game_launch: "07-20-2022",
    provider: "AllWaySpin",
    features: ["Quickspin", "Tumbling reels", "Increasing multipliers"],
    theme: "Jungle",
    volatility: "low-medium"
  }
]
